# jekyll serve -w
name: Prototype Views
exclude: [Gemfile, Gemfile.lock, .gitignore, README.md]
domain: http://malmostad.github.io
baseurl: /prototypes
external_cdn_url: //assets.malmo.se/external/v4-staging
# external_cdn_url: //www.local.malmo.se:3001/assets
internal_cdn_url: //assets.malmo.se/internal/v4-staging
# internal_cdn_url: //www.local.malmo.se:3001/assets

collections:
  internal_pages:
    output: true
    permalink: /internal/:path/
  external_pages:
    output: true
    permalink: /external/:path/

defaults:
  -
    scope:
      path: ""
      type: "internal_pages"
    values:
      layout: "internal-default"
  -
    scope:
      path: ""
      type: "external_pages"
    values:
      layout: "external-default"

sass:
  style: :compressed

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: rsquo,rsquo,rdquo,rdquo
  use_coderay: false
